networks:
  proxy:
    name: proxy
  appwrite:
    name: appwrite
  runtimes:
    name: runtimes

volumes:
  letsencrypt:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-config:
  minecraft-world:
  minecraft-world-nether:
  minecraft-world-the-end:
