services:
  bedrock:
    image: ghcr.io/haepapa/minecraft-server:${BEDROCK_BRANCH}
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      - traefik.udp.routers.bedrock.entrypoints=bedrock
      - traefik.udp.routers.bedrock.service=bedrock
      - traefik.udp.services.bedrock.loadbalancer.server.port=19132
    networks:
      - proxy
    volumes:
      - bedrock-worlds:/minecraft/worlds:rw
